#!/usr/bin/env php
<?php

/**
 * |----------------------------------------------------------------
 * |             ***** Composer Auto Loader *****
 * |----------------------------------------------------------------
 */
require __DIR__.'/vendor/autoload.php';

(require_once __DIR__ . '/bootstrap/app.php')
    ->handleCommands();
